"""add missing columns cotizaciones pedidos_clientes

Revision ID: 8aa3dffe7aa3
Revises: 20260419_0002
Create Date: 2026-04-22 20:09:04.182641
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8aa3dffe7aa3"
down_revision: str | None = "20260419_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # staging.csv_* tables already exist — skipped
    op.drop_constraint(op.f("categorias_name_key"), "categorias", type_="unique")
    op.create_index(op.f("ix_categorias_name"), "categorias", ["name"], unique=True)
    op.add_column(
        "clientes", sa.Column("short_code", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "clientes", sa.Column("legal_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "clientes", sa.Column("website", sa.String(length=255), nullable=True)
    )
    op.add_column("clientes", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("clientes", sa.Column("created_by_user_id", sa.UUID(), nullable=True))
    # clientes.category type change skipped — VARCHAR(80→40)
    op.create_index(
        op.f("ix_clientes_short_code"), "clientes", ["short_code"], unique=False
    )
    op.create_foreign_key(
        None, "clientes", "users", ["created_by_user_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "cotizaciones", sa.Column("po_pr", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "cotizaciones", sa.Column("file_url", sa.String(length=500), nullable=True)
    )
    op.add_column("cotizaciones", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "cotizaciones", sa.Column("quote_status", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "cotizaciones", sa.Column("approval_days", sa.Integer(), nullable=True)
    )
    op.add_column(
        "cotizaciones", sa.Column("approved_by_user_id", sa.UUID(), nullable=True)
    )
    # cotizaciones.discount type change skipped — used by generated column
    op.create_index(
        op.f("ix_cotizaciones_po_pr"), "cotizaciones", ["po_pr"], unique=False
    )
    op.create_foreign_key(
        None,
        "cotizaciones",
        "users",
        ["approved_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "cotizaciones_canceladas",
        sa.Column("cancellation_reason", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "cotizaciones_canceladas",
        sa.Column("evidence_url", sa.String(length=500), nullable=True),
    )
    op.add_column("entradas_mercancia", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "entradas_mercancia", sa.Column("created_by_user_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "entradas_mercancia",
        sa.Column("last_edited_by_user_id", sa.UUID(), nullable=True),
    )
    # entradas_mercancia type changes skipped — incompatible cast or generated columns
    op.create_foreign_key(
        None,
        "entradas_mercancia",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "entradas_mercancia",
        "users",
        ["last_edited_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("facturas_compras", sa.Column("comments", sa.Text(), nullable=True))
    op.add_column(
        "facturas_compras", sa.Column("cfdi_usage", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "facturas_compras",
        sa.Column(
            "shipping_insurance", sa.Numeric(precision=14, scale=4), nullable=True
        ),
    )
    op.add_column(
        "facturas_compras", sa.Column("payment_methods", sa.JSON(), nullable=True)
    )
    op.add_column(
        "facturas_compras", sa.Column("task_assigned", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "facturas_compras",
        sa.Column("invoice_file_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "facturas_compras",
        sa.Column("material_evidence_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "facturas_compras", sa.Column("created_by_user_id", sa.UUID(), nullable=True)
    )
    # facturas_compras type changes skipped — generated columns
    op.create_foreign_key(
        None,
        "facturas_compras",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "gastos_operativos",
        sa.Column("account_card_number", sa.String(length=80), nullable=True),
    )
    op.add_column("gastos_operativos", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "gastos_operativos", sa.Column("file_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "gastos_operativos", sa.Column("created_by_user_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "gastos_operativos",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("marcas_name_key"), "marcas", type_="unique")
    op.create_index(op.f("ix_marcas_name"), "marcas", ["name"], unique=True)
    op.create_index(
        op.f("ix_movimientos_inventario_goods_receipt_id"),
        "movimientos_inventario",
        ["goods_receipt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimientos_inventario_movement_number"),
        "movimientos_inventario",
        ["movement_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimientos_inventario_nonconformity_id"),
        "movimientos_inventario",
        ["nonconformity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimientos_inventario_quote_item_id"),
        "movimientos_inventario",
        ["quote_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "movimientos_inventario",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "no_conformes",
        sa.Column("photo_evidence_url", sa.String(length=500), nullable=True),
    )
    # no_conformes type changes skipped — generated columns
    op.create_index(
        op.f("ix_no_conformes_reason"), "no_conformes", ["reason"], unique=False
    )
    op.drop_column("no_conformes", "notes")
    op.add_column(
        "pedidos_clientes",
        sa.Column("invoice_number", sa.String(length=120), nullable=True),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("delivery_note_number", sa.String(length=120), nullable=True),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("payment_complement_number", sa.String(length=120), nullable=True),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("received_by", sa.String(length=255), nullable=True),
    )
    op.add_column("pedidos_clientes", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "pedidos_clientes",
        sa.Column("invoice_file_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("delivery_note_file_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "pedidos_clientes", sa.Column("invoice_status_multi", sa.JSON(), nullable=True)
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("invoice_state", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "pedidos_clientes", sa.Column("secondary_paid_on", sa.Date(), nullable=True)
    )
    op.add_column(
        "pedidos_clientes", sa.Column("secondary_invoiced_on", sa.Date(), nullable=True)
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("secondary_validated_on", sa.Date(), nullable=True),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("secondary_associated_on", sa.Date(), nullable=True),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column("fulfillment_responsible_user_id", sa.UUID(), nullable=True),
    )
    # pedidos_clientes.packed_percent type change skipped — generated column dependency
    op.create_foreign_key(
        None,
        "pedidos_clientes",
        "users",
        ["fulfillment_responsible_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("pedidos_clientes", "preparation_times")
    op.drop_column("pedidos_clientes", "delivery_time")
    op.drop_column("pedidos_clientes", "payment_times")
    op.add_column(
        "pedidos_incompletos", sa.Column("name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "pedidos_incompletos", sa.Column("additional_notes", sa.Text(), nullable=True)
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("priority", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "pedidos_incompletos", sa.Column("status", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("estimated_resolution_on", sa.Date(), nullable=True),
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("responsible", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("responsible_user_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "pedidos_incompletos", sa.Column("quote_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("customer_final_id", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("missing_products", sa.Integer(), nullable=True),
    )
    op.add_column(
        "pedidos_incompletos",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.alter_column(
        "pedidos_incompletos",
        "reason",
        existing_type=sa.TEXT(),
        type_=sa.String(length=80),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_pedidos_incompletos_name"),
        "pedidos_incompletos",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_incompletos_priority"),
        "pedidos_incompletos",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_incompletos_quote_id"),
        "pedidos_incompletos",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_incompletos_status"),
        "pedidos_incompletos",
        ["status"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "pedidos_incompletos",
        "users",
        ["responsible_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "pedidos_incompletos",
        "cotizaciones",
        ["quote_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # productos.package_size type change skipped — generated column dependency
    op.create_index(
        op.f("ix_productos_brand_id"), "productos", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_productos_category_id"), "productos", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_productos_sat_code"), "productos", ["sat_code"], unique=False
    )
    op.add_column(
        "proveedores", sa.Column("short_code", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "proveedores", sa.Column("legal_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "proveedores", sa.Column("website", sa.String(length=255), nullable=True)
    )
    op.add_column("proveedores", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "proveedores", sa.Column("created_by_user_id", sa.UUID(), nullable=True)
    )
    # proveedores.category type change skipped — VARCHAR(80→40)
    op.create_index(
        op.f("ix_proveedores_short_code"), "proveedores", ["short_code"], unique=False
    )
    op.create_foreign_key(
        None,
        "proveedores",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("solicitudes_material", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "solicitudes_material",
        sa.Column("supplier_contact_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "solicitudes_material",
        sa.Column("supplier_contact_email", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "solicitudes_material",
        sa.Column("supplier_contact_phone", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "solicitudes_material", sa.Column("supplier_address", sa.Text(), nullable=True)
    )
    op.add_column(
        "solicitudes_material",
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "solicitudes_material",
        sa.Column("last_edited_by_user_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "solicitudes_material",
        "users",
        ["last_edited_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "solicitudes_material",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("ventas", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "verificador_fechas_pedidos",
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "verificador_fechas_pedidos", sa.Column("customer_id", sa.UUID(), nullable=True)
    )
    # verificador_fechas_pedidos.event_type type change skipped
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_customer_id"),
        "verificador_fechas_pedidos",
        ["customer_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "verificador_fechas_pedidos",
        "users",
        ["triggered_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "verificador_fechas_pedidos",
        "clientes",
        ["customer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verificador_fechas_pedidos", type_="foreignkey")
    op.drop_constraint(None, "verificador_fechas_pedidos", type_="foreignkey")
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_customer_id"),
        table_name="verificador_fechas_pedidos",
    )
    op.alter_column(
        "verificador_fechas_pedidos",
        "event_type",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.drop_column("verificador_fechas_pedidos", "customer_id")
    op.drop_column("verificador_fechas_pedidos", "triggered_by_user_id")
    op.drop_column("ventas", "notes")
    op.drop_constraint(None, "solicitudes_material", type_="foreignkey")
    op.drop_constraint(None, "solicitudes_material", type_="foreignkey")
    op.drop_column("solicitudes_material", "last_edited_by_user_id")
    op.drop_column("solicitudes_material", "created_by_user_id")
    op.drop_column("solicitudes_material", "supplier_address")
    op.drop_column("solicitudes_material", "supplier_contact_phone")
    op.drop_column("solicitudes_material", "supplier_contact_email")
    op.drop_column("solicitudes_material", "supplier_contact_name")
    op.drop_column("solicitudes_material", "notes")
    op.drop_constraint(None, "proveedores", type_="foreignkey")
    op.drop_index(op.f("ix_proveedores_short_code"), table_name="proveedores")
    op.alter_column(
        "proveedores",
        "category",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.drop_column("proveedores", "created_by_user_id")
    op.drop_column("proveedores", "notes")
    op.drop_column("proveedores", "website")
    op.drop_column("proveedores", "legal_name")
    op.drop_column("proveedores", "short_code")
    op.drop_index(op.f("ix_productos_sat_code"), table_name="productos")
    op.drop_index(op.f("ix_productos_category_id"), table_name="productos")
    op.drop_index(op.f("ix_productos_brand_id"), table_name="productos")
    op.alter_column(
        "productos",
        "package_size",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.VARCHAR(length=40),
        existing_nullable=True,
    )
    op.drop_constraint(None, "pedidos_incompletos", type_="foreignkey")
    op.drop_constraint(None, "pedidos_incompletos", type_="foreignkey")
    op.drop_index(
        op.f("ix_pedidos_incompletos_status"), table_name="pedidos_incompletos"
    )
    op.drop_index(
        op.f("ix_pedidos_incompletos_quote_id"), table_name="pedidos_incompletos"
    )
    op.drop_index(
        op.f("ix_pedidos_incompletos_priority"), table_name="pedidos_incompletos"
    )
    op.drop_index(op.f("ix_pedidos_incompletos_name"), table_name="pedidos_incompletos")
    op.alter_column(
        "pedidos_incompletos",
        "reason",
        existing_type=sa.String(length=80),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("pedidos_incompletos", "updated_at")
    op.drop_column("pedidos_incompletos", "missing_products")
    op.drop_column("pedidos_incompletos", "customer_final_id")
    op.drop_column("pedidos_incompletos", "quote_id")
    op.drop_column("pedidos_incompletos", "responsible_user_id")
    op.drop_column("pedidos_incompletos", "responsible")
    op.drop_column("pedidos_incompletos", "estimated_resolution_on")
    op.drop_column("pedidos_incompletos", "status")
    op.drop_column("pedidos_incompletos", "priority")
    op.drop_column("pedidos_incompletos", "additional_notes")
    op.drop_column("pedidos_incompletos", "name")
    op.add_column(
        "pedidos_clientes",
        sa.Column(
            "payment_times", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column(
            "delivery_time", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "pedidos_clientes",
        sa.Column(
            "preparation_times",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "pedidos_clientes", type_="foreignkey")
    op.alter_column(
        "pedidos_clientes",
        "packed_percent",
        existing_type=sa.Numeric(precision=6, scale=2),
        type_=sa.VARCHAR(length=40),
        existing_nullable=True,
    )
    op.drop_column("pedidos_clientes", "fulfillment_responsible_user_id")
    op.drop_column("pedidos_clientes", "secondary_associated_on")
    op.drop_column("pedidos_clientes", "secondary_validated_on")
    op.drop_column("pedidos_clientes", "secondary_invoiced_on")
    op.drop_column("pedidos_clientes", "secondary_paid_on")
    op.drop_column("pedidos_clientes", "invoice_state")
    op.drop_column("pedidos_clientes", "invoice_status_multi")
    op.drop_column("pedidos_clientes", "delivery_note_file_url")
    op.drop_column("pedidos_clientes", "invoice_file_url")
    op.drop_column("pedidos_clientes", "notes")
    op.drop_column("pedidos_clientes", "received_by")
    op.drop_column("pedidos_clientes", "payment_complement_number")
    op.drop_column("pedidos_clientes", "delivery_note_number")
    op.drop_column("pedidos_clientes", "invoice_number")
    op.add_column(
        "no_conformes",
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_no_conformes_reason"), table_name="no_conformes")
    op.alter_column(
        "no_conformes",
        "adjustment_type",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.alter_column(
        "no_conformes",
        "action_taken",
        existing_type=sa.String(length=80),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "no_conformes",
        "reason",
        existing_type=sa.String(length=80),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("no_conformes", "photo_evidence_url")
    op.drop_constraint(None, "movimientos_inventario", type_="foreignkey")
    op.drop_index(
        op.f("ix_movimientos_inventario_quote_item_id"),
        table_name="movimientos_inventario",
    )
    op.drop_index(
        op.f("ix_movimientos_inventario_nonconformity_id"),
        table_name="movimientos_inventario",
    )
    op.drop_index(
        op.f("ix_movimientos_inventario_movement_number"),
        table_name="movimientos_inventario",
    )
    op.drop_index(
        op.f("ix_movimientos_inventario_goods_receipt_id"),
        table_name="movimientos_inventario",
    )
    op.drop_index(op.f("ix_marcas_name"), table_name="marcas")
    op.create_unique_constraint(
        op.f("marcas_name_key"), "marcas", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(None, "gastos_operativos", type_="foreignkey")
    op.drop_column("gastos_operativos", "created_by_user_id")
    op.drop_column("gastos_operativos", "file_url")
    op.drop_column("gastos_operativos", "notes")
    op.drop_column("gastos_operativos", "account_card_number")
    op.drop_constraint(None, "facturas_compras", type_="foreignkey")
    op.alter_column(
        "facturas_compras",
        "delivered_percent",
        existing_type=sa.Numeric(precision=6, scale=4),
        type_=sa.NUMERIC(precision=6, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "facturas_compras",
        "purchase_type",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.drop_column("facturas_compras", "created_by_user_id")
    op.drop_column("facturas_compras", "material_evidence_url")
    op.drop_column("facturas_compras", "invoice_file_url")
    op.drop_column("facturas_compras", "task_assigned")
    op.drop_column("facturas_compras", "payment_methods")
    op.drop_column("facturas_compras", "shipping_insurance")
    op.drop_column("facturas_compras", "cfdi_usage")
    op.drop_column("facturas_compras", "comments")
    op.drop_constraint(None, "entradas_mercancia", type_="foreignkey")
    op.drop_constraint(None, "entradas_mercancia", type_="foreignkey")
    op.alter_column(
        "entradas_mercancia",
        "tdp",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.alter_column(
        "entradas_mercancia",
        "physical_validation",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.drop_column("entradas_mercancia", "last_edited_by_user_id")
    op.drop_column("entradas_mercancia", "created_by_user_id")
    op.drop_column("entradas_mercancia", "notes")
    op.drop_column("cotizaciones_canceladas", "evidence_url")
    op.drop_column("cotizaciones_canceladas", "cancellation_reason")
    op.drop_constraint(None, "cotizaciones", type_="foreignkey")
    op.drop_index(op.f("ix_cotizaciones_po_pr"), table_name="cotizaciones")
    op.alter_column(
        "cotizaciones",
        "discount",
        existing_type=sa.Numeric(precision=6, scale=4),
        type_=sa.NUMERIC(precision=14, scale=4),
        existing_nullable=True,
    )
    op.drop_column("cotizaciones", "approved_by_user_id")
    op.drop_column("cotizaciones", "approval_days")
    op.drop_column("cotizaciones", "quote_status")
    op.drop_column("cotizaciones", "notes")
    op.drop_column("cotizaciones", "file_url")
    op.drop_column("cotizaciones", "po_pr")
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.drop_index(op.f("ix_clientes_short_code"), table_name="clientes")
    op.alter_column(
        "clientes",
        "category",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    op.drop_column("clientes", "created_by_user_id")
    op.drop_column("clientes", "notes")
    op.drop_column("clientes", "website")
    op.drop_column("clientes", "legal_name")
    op.drop_column("clientes", "short_code")
    op.drop_index(op.f("ix_categorias_name"), table_name="categorias")
    op.create_unique_constraint(
        op.f("categorias_name_key"),
        "categorias",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # staging.csv_* tables were pre-existing — not dropped
    # ### end Alembic commands ###
