"""create ops + staging tables

Revision ID: f6a0e4534684
Revises: 20260418_0001
Create Date: 2026-04-19 16:03:32.754682
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6a0e4534684"
down_revision: str | None = "20260418_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS staging")
    op.create_table(
        "clientes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("rfc", sa.String(length=20), nullable=True),
        sa.Column("main_contact", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("annual_purchase", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("last_purchase_date", sa.Date(), nullable=True),
        sa.Column("avg_payment_days", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clientes_external_id"), "clientes", ["external_id"], unique=True
    )
    op.create_index(op.f("ix_clientes_name"), "clientes", ["name"], unique=False)
    op.create_table(
        "crecimiento_inventario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("registered_on", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("growth_type", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crecimiento_inventario_growth_type"),
        "crecimiento_inventario",
        ["growth_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crecimiento_inventario_name"),
        "crecimiento_inventario",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crecimiento_inventario_registered_on"),
        "crecimiento_inventario",
        ["registered_on"],
        unique=False,
    )
    op.create_table(
        "csv_import_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset", sa.String(length=80), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("inserted_count", sa.Integer(), nullable=True),
        sa.Column("updated_count", sa.Integer(), nullable=True),
        sa.Column("skipped_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_csv_import_runs_dataset"), "csv_import_runs", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_csv_import_runs_started_at"),
        "csv_import_runs",
        ["started_at"],
        unique=False,
    )
    op.create_table(
        "productos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=True),
        sa.Column("internal_code", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("sale_type", sa.String(length=40), nullable=True),
        sa.Column("package_size", sa.String(length=40), nullable=True),
        sa.Column("brand", sa.String(length=80), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "purchase_cost_parts", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column(
            "purchase_cost_ariba", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_productos_category"), "productos", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_productos_internal_code"), "productos", ["internal_code"], unique=True
    )
    op.create_index(op.f("ix_productos_name"), "productos", ["name"], unique=False)
    op.create_index(op.f("ix_productos_sku"), "productos", ["sku"], unique=True)
    op.create_table(
        "proveedores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("rfc", sa.String(length=20), nullable=True),
        sa.Column("main_contact", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("annual_purchase", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("last_purchase_date", sa.Date(), nullable=True),
        sa.Column("avg_payment_days", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proveedores_external_id"), "proveedores", ["external_id"], unique=True
    )
    op.create_index(op.f("ix_proveedores_name"), "proveedores", ["name"], unique=False)
    op.create_table(
        "csv_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset", sa.String(length=80), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("delimiter", sa.String(length=5), nullable=True),
        sa.Column("encoding", sa.String(length=40), nullable=True),
        sa.Column("header", sa.JSON(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="staging",
    )
    op.create_index(
        "ix_csv_files_dataset", "csv_files", ["dataset"], unique=False, schema="staging"
    )
    op.create_index(
        "ix_csv_files_uploaded_at",
        "csv_files",
        ["uploaded_at"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "cotizaciones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("order_status", sa.String(length=40), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("external_customer_id", sa.String(length=80), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("followed_up_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discount", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("credit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("months", sa.Integer(), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "purchase_subtotal", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("payment_time", sa.String(length=80), nullable=True),
        sa.Column("payment_type", sa.String(length=80), nullable=True),
        sa.Column("missing_products", sa.Integer(), nullable=True),
        sa.Column("packed_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("ariba_status", sa.String(length=80), nullable=True),
        sa.Column("customer_code", sa.String(length=40), nullable=True),
        sa.Column("delivery_role", sa.String(length=80), nullable=True),
        sa.Column("packed_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["clientes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cotizaciones_created_on"), "cotizaciones", ["created_on"], unique=False
    )
    op.create_index(
        op.f("ix_cotizaciones_customer_code"),
        "cotizaciones",
        ["customer_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_customer_id"),
        "cotizaciones",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_external_customer_id"),
        "cotizaciones",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_name"), "cotizaciones", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_cotizaciones_order_status"),
        "cotizaciones",
        ["order_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_status"), "cotizaciones", ["status"], unique=False
    )
    op.create_table(
        "facturas_compras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quote_number", sa.String(length=80), nullable=True),
        sa.Column("invoice_number", sa.String(length=80), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("external_supplier_id", sa.String(length=80), nullable=True),
        sa.Column("supplier_rfc", sa.String(length=20), nullable=True),
        sa.Column("received_on", sa.Date(), nullable=True),
        sa.Column("invoice_on", sa.Date(), nullable=True),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column(
            "shipping_insurance_discount",
            sa.Numeric(precision=14, scale=4),
            nullable=True,
        ),
        sa.Column("purchase_type", sa.String(length=80), nullable=True),
        sa.Column("payment_type", sa.String(length=80), nullable=True),
        sa.Column("order_status", sa.String(length=40), nullable=True),
        sa.Column("payment_status", sa.String(length=40), nullable=True),
        sa.Column("invoice_status", sa.String(length=40), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("iva", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("delivered_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("related_goods_receipts", sa.JSON(), nullable=True),
        sa.Column("review_responsible", sa.String(length=255), nullable=True),
        sa.Column("related_nonconformities", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("subtotal >= 0", name="ck_facturas_compras_subtotal_nonneg"),
        sa.CheckConstraint("total >= 0", name="ck_facturas_compras_total_nonneg"),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["proveedores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_facturas_compras_external_supplier_id"),
        "facturas_compras",
        ["external_supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_invoice_number"),
        "facturas_compras",
        ["invoice_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_invoice_on"),
        "facturas_compras",
        ["invoice_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_invoice_status"),
        "facturas_compras",
        ["invoice_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_order_status"),
        "facturas_compras",
        ["order_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_payment_status"),
        "facturas_compras",
        ["payment_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_quote_number"),
        "facturas_compras",
        ["quote_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facturas_compras_supplier_id"),
        "facturas_compras",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "gastos_operativos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("concept", sa.String(length=255), nullable=False),
        sa.Column("invoice_folio", sa.String(length=120), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("iva", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("spent_on", sa.Date(), nullable=True),
        sa.Column("is_deductible", sa.Boolean(), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("payment_method", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("responsible", sa.String(length=255), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("supplier_name", sa.String(length=255), nullable=True),
        sa.Column("supplier_rfc", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total >= 0", name="ck_gastos_operativos_total_nonneg"),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["proveedores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gastos_operativos_category"),
        "gastos_operativos",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gastos_operativos_invoice_folio"),
        "gastos_operativos",
        ["invoice_folio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gastos_operativos_is_deductible"),
        "gastos_operativos",
        ["is_deductible"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gastos_operativos_payment_method"),
        "gastos_operativos",
        ["payment_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gastos_operativos_spent_on"),
        "gastos_operativos",
        ["spent_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gastos_operativos_status"),
        "gastos_operativos",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gastos_operativos_supplier_id"),
        "gastos_operativos",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "inventario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_product_id", sa.String(length=80), nullable=True),
        sa.Column("internal_code", sa.String(length=80), nullable=True),
        sa.Column("real_qty", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("theoretical_qty", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("stock_diff", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("stock_total_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("status_real", sa.String(length=40), nullable=True),
        sa.Column("stock_alert", sa.String(length=40), nullable=True),
        sa.Column("purchase_block", sa.Boolean(), nullable=True),
        sa.Column("days_without_movement", sa.Integer(), nullable=True),
        sa.Column("movement_traffic_light", sa.String(length=40), nullable=True),
        sa.Column("aging_classification", sa.String(length=40), nullable=True),
        sa.Column("rotation_classification", sa.String(length=40), nullable=True),
        sa.Column("abc_classification", sa.String(length=40), nullable=True),
        sa.Column("suggested_action", sa.String(length=255), nullable=True),
        sa.Column("last_inbound_on", sa.Date(), nullable=True),
        sa.Column("last_outbound_on", sa.Date(), nullable=True),
        sa.Column("demand_history", sa.String(length=80), nullable=True),
        sa.Column(
            "total_accumulated_sales", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=True),
        sa.Column("physical_diff", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventario_external_product_id"),
        "inventario",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventario_internal_code"),
        "inventario",
        ["internal_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventario_product_id"), "inventario", ["product_id"], unique=False
    )
    op.create_table(
        "movimientos_inventario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_product_id", sa.String(length=80), nullable=True),
        sa.Column("movement_type", sa.String(length=40), nullable=True),
        sa.Column("qty_in", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("qty_out", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("moved_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origin", sa.String(length=255), nullable=True),
        sa.Column("destination", sa.String(length=255), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_movimientos_inventario_external_product_id"),
        "movimientos_inventario",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimientos_inventario_moved_on"),
        "movimientos_inventario",
        ["moved_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimientos_inventario_movement_type"),
        "movimientos_inventario",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_movimientos_inventario_product_id"),
        "movimientos_inventario",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "solicitudes_material",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("product_sku", sa.String(length=80), nullable=True),
        sa.Column("external_product_id", sa.String(length=80), nullable=True),
        sa.Column("qty_requested", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "qty_requested_converted", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("requested_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("external_supplier_id", sa.String(length=80), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("package_size", sa.String(length=80), nullable=True),
        sa.Column("days_without_movement", sa.Integer(), nullable=True),
        sa.Column("blocked_by_dormant_inventory", sa.Boolean(), nullable=True),
        sa.Column("purchase_exception_reason", sa.Text(), nullable=True),
        sa.Column("demand_history", sa.String(length=80), nullable=True),
        sa.Column("last_valid_outbound_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["proveedores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_solicitudes_material_external_product_id"),
        "solicitudes_material",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solicitudes_material_external_supplier_id"),
        "solicitudes_material",
        ["external_supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solicitudes_material_product_id"),
        "solicitudes_material",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solicitudes_material_product_sku"),
        "solicitudes_material",
        ["product_sku"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solicitudes_material_requested_on"),
        "solicitudes_material",
        ["requested_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solicitudes_material_status"),
        "solicitudes_material",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solicitudes_material_supplier_id"),
        "solicitudes_material",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "csv_row_errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("csv_file_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["csv_file_id"], ["staging.csv_files.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="staging",
    )
    op.create_index(
        "ix_csv_row_errors_file_row_number",
        "csv_row_errors",
        ["csv_file_id", "row_number"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "csv_rows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("csv_file_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["csv_file_id"], ["staging.csv_files.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="staging",
    )
    op.create_index(
        "ix_csv_rows_file_row_number",
        "csv_rows",
        ["csv_file_id", "row_number"],
        unique=True,
        schema="staging",
    )
    op.create_table(
        "cotizacion_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quote_id", sa.UUID(), nullable=False),
        sa.Column("line_external_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_product_id", sa.String(length=80), nullable=True),
        sa.Column("sku", sa.String(length=80), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("qty_requested", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("qty_packed", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("qty_missing", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "unit_cost_purchase", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("unit_cost_sale", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "purchase_subtotal", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column(
            "accumulated_sales", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("last_90_days", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("last_180_days", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("quote_status", sa.String(length=40), nullable=True),
        sa.Column("external_customer_id", sa.String(length=80), nullable=True),
        sa.Column("last_updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["quote_id"], ["cotizaciones.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "quote_id", "line_external_id", name="uq_cotizacion_items_quote_line"
        ),
    )
    op.create_index(
        op.f("ix_cotizacion_items_external_customer_id"),
        "cotizacion_items",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizacion_items_external_product_id"),
        "cotizacion_items",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizacion_items_product_id"),
        "cotizacion_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizacion_items_quote_id"),
        "cotizacion_items",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizacion_items_sku"), "cotizacion_items", ["sku"], unique=False
    )
    op.create_index(
        op.f("ix_cotizacion_items_status"), "cotizacion_items", ["status"], unique=False
    )
    op.create_table(
        "cotizaciones_canceladas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quote_number", sa.String(length=120), nullable=True),
        sa.Column("cancelled_on", sa.Date(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("quote_id", sa.UUID(), nullable=True),
        sa.Column("external_customer_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["quote_id"], ["cotizaciones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cotizaciones_canceladas_cancelled_on"),
        "cotizaciones_canceladas",
        ["cancelled_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_canceladas_external_customer_id"),
        "cotizaciones_canceladas",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_canceladas_quote_id"),
        "cotizaciones_canceladas",
        ["quote_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizaciones_canceladas_quote_number"),
        "cotizaciones_canceladas",
        ["quote_number"],
        unique=False,
    )
    op.create_table(
        "entradas_mercancia",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_number", sa.String(length=80), nullable=True),
        sa.Column("qty_requested", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("qty_arrived", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("external_supplier_id", sa.String(length=80), nullable=True),
        sa.Column("internal_code", sa.String(length=80), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_product_id", sa.String(length=80), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("received_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("physical_validation", sa.String(length=80), nullable=True),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("payment_status", sa.String(length=40), nullable=True),
        sa.Column("payment_type", sa.String(length=80), nullable=True),
        sa.Column("purchase_invoice_id", sa.UUID(), nullable=True),
        sa.Column("tdp", sa.String(length=80), nullable=True),
        sa.Column(
            "qty_requested_converted", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("validated_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["purchase_invoice_id"], ["facturas_compras.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["proveedores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entradas_mercancia_entry_number"),
        "entradas_mercancia",
        ["entry_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_external_product_id"),
        "entradas_mercancia",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_external_supplier_id"),
        "entradas_mercancia",
        ["external_supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_internal_code"),
        "entradas_mercancia",
        ["internal_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_product_id"),
        "entradas_mercancia",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_purchase_invoice_id"),
        "entradas_mercancia",
        ["purchase_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_received_on"),
        "entradas_mercancia",
        ["received_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entradas_mercancia_supplier_id"),
        "entradas_mercancia",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "pedidos_clientes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("external_customer_id", sa.String(length=80), nullable=True),
        sa.Column("customer_code", sa.String(length=40), nullable=True),
        sa.Column("payment_type", sa.String(length=80), nullable=True),
        sa.Column("invoice_status", sa.String(length=40), nullable=True),
        sa.Column("order_status", sa.String(length=40), nullable=True),
        sa.Column("payment_status", sa.String(length=40), nullable=True),
        sa.Column("ordered_on", sa.Date(), nullable=True),
        sa.Column("validated_on", sa.Date(), nullable=True),
        sa.Column("approved_on", sa.Date(), nullable=True),
        sa.Column("associated_on", sa.Date(), nullable=True),
        sa.Column("shipped_on", sa.Date(), nullable=True),
        sa.Column("delivered_on", sa.Date(), nullable=True),
        sa.Column("invoiced_on", sa.Date(), nullable=True),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("fulfillment_responsible", sa.String(length=255), nullable=True),
        sa.Column("quote_id", sa.UUID(), nullable=True),
        sa.Column("has_missing_items", sa.Boolean(), nullable=True),
        sa.Column("delivery_type", sa.String(length=80), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "subtotal_with_shipping", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("delivery_time", sa.String(length=80), nullable=True),
        sa.Column("payment_times", sa.String(length=80), nullable=True),
        sa.Column("preparation_times", sa.String(length=80), nullable=True),
        sa.Column("packed_percent", sa.String(length=40), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["clientes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["quote_id"], ["cotizaciones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pedidos_clientes_customer_code"),
        "pedidos_clientes",
        ["customer_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_clientes_customer_id"),
        "pedidos_clientes",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_clientes_external_customer_id"),
        "pedidos_clientes",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_clientes_name"), "pedidos_clientes", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_pedidos_clientes_order_status"),
        "pedidos_clientes",
        ["order_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_clientes_ordered_on"),
        "pedidos_clientes",
        ["ordered_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_clientes_payment_status"),
        "pedidos_clientes",
        ["payment_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_clientes_quote_id"),
        "pedidos_clientes",
        ["quote_id"],
        unique=False,
    )
    op.create_table(
        "pedidos_proveedor",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_folio", sa.String(length=80), nullable=True),
        sa.Column("order_status", sa.String(length=40), nullable=True),
        sa.Column("pickup_status", sa.String(length=40), nullable=True),
        sa.Column("generated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_on", sa.Date(), nullable=True),
        sa.Column("confirmed_on", sa.Date(), nullable=True),
        sa.Column("estimated_pickup_on", sa.Date(), nullable=True),
        sa.Column("pickup_on", sa.Date(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("external_supplier_id", sa.String(length=80), nullable=True),
        sa.Column("products_requested", sa.JSON(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("iva", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=True),
        sa.Column("sent_by_email", sa.Boolean(), nullable=True),
        sa.Column("is_printed", sa.Boolean(), nullable=True),
        sa.Column("followup_responsibles", sa.JSON(), nullable=True),
        sa.Column("purchase_invoice_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["purchase_invoice_id"], ["facturas_compras.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["proveedores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_external_supplier_id"),
        "pedidos_proveedor",
        ["external_supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_generated_on"),
        "pedidos_proveedor",
        ["generated_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_order_folio"),
        "pedidos_proveedor",
        ["order_folio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_order_status"),
        "pedidos_proveedor",
        ["order_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_pickup_status"),
        "pedidos_proveedor",
        ["pickup_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_purchase_invoice_id"),
        "pedidos_proveedor",
        ["purchase_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_proveedor_supplier_id"),
        "pedidos_proveedor",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "ventas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sold_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("external_customer_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("purchase_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("gross_margin", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("margin_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("diff_vs_po", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("packed_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("year_month", sa.String(length=20), nullable=True),
        sa.Column("quadrimester", sa.String(length=20), nullable=True),
        sa.Column("status_r", sa.String(length=40), nullable=True),
        sa.Column("quote_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["clientes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["quote_id"], ["cotizaciones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ventas_customer_id"), "ventas", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_ventas_external_customer_id"),
        "ventas",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ventas_name"), "ventas", ["name"], unique=False)
    op.create_index(
        op.f("ix_ventas_quadrimester"), "ventas", ["quadrimester"], unique=False
    )
    op.create_index(op.f("ix_ventas_quote_id"), "ventas", ["quote_id"], unique=False)
    op.create_index(op.f("ix_ventas_sold_on"), "ventas", ["sold_on"], unique=False)
    op.create_index(op.f("ix_ventas_status"), "ventas", ["status"], unique=False)
    op.create_index(
        op.f("ix_ventas_year_month"), "ventas", ["year_month"], unique=False
    )
    op.create_table(
        "no_conformes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("folio", sa.String(length=80), nullable=True),
        sa.Column("detected_on", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("action_taken", sa.Text(), nullable=True),
        sa.Column("adjustment_type", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_product_id", sa.String(length=80), nullable=True),
        sa.Column("inventory_item_id", sa.UUID(), nullable=True),
        sa.Column("purchase_invoice_id", sa.UUID(), nullable=True),
        sa.Column("customer_order_id", sa.UUID(), nullable=True),
        sa.Column("detected_by", sa.String(length=255), nullable=True),
        sa.Column("inventory_adjustment", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("temporary_physical_location", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_order_id"], ["pedidos_clientes.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"], ["inventario.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["purchase_invoice_id"], ["facturas_compras.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_no_conformes_customer_order_id"),
        "no_conformes",
        ["customer_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_no_conformes_detected_on"),
        "no_conformes",
        ["detected_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_no_conformes_external_product_id"),
        "no_conformes",
        ["external_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_no_conformes_folio"), "no_conformes", ["folio"], unique=False
    )
    op.create_index(
        op.f("ix_no_conformes_inventory_item_id"),
        "no_conformes",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_no_conformes_product_id"), "no_conformes", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_no_conformes_purchase_invoice_id"),
        "no_conformes",
        ["purchase_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_no_conformes_status"), "no_conformes", ["status"], unique=False
    )
    op.create_table(
        "pedidos_incompletos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_order_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("aging_days", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_order_id"], ["pedidos_clientes.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["productos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pedidos_incompletos_customer_order_id"),
        "pedidos_incompletos",
        ["customer_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedidos_incompletos_product_id"),
        "pedidos_incompletos",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "verificador_fechas_pedidos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_order_id", sa.UUID(), nullable=True),
        sa.Column("order_name", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("event_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by", sa.String(length=255), nullable=True),
        sa.Column("external_customer_id", sa.String(length=80), nullable=True),
        sa.Column("quote_id", sa.UUID(), nullable=True),
        sa.Column("order_link", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_order_id"], ["pedidos_clientes.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["quote_id"], ["cotizaciones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_customer_order_id"),
        "verificador_fechas_pedidos",
        ["customer_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_event_date"),
        "verificador_fechas_pedidos",
        ["event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_event_type"),
        "verificador_fechas_pedidos",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_external_customer_id"),
        "verificador_fechas_pedidos",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_order_name"),
        "verificador_fechas_pedidos",
        ["order_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verificador_fechas_pedidos_quote_id"),
        "verificador_fechas_pedidos",
        ["quote_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_quote_id"),
        table_name="verificador_fechas_pedidos",
    )
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_order_name"),
        table_name="verificador_fechas_pedidos",
    )
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_external_customer_id"),
        table_name="verificador_fechas_pedidos",
    )
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_event_type"),
        table_name="verificador_fechas_pedidos",
    )
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_event_date"),
        table_name="verificador_fechas_pedidos",
    )
    op.drop_index(
        op.f("ix_verificador_fechas_pedidos_customer_order_id"),
        table_name="verificador_fechas_pedidos",
    )
    op.drop_table("verificador_fechas_pedidos")
    op.drop_index(
        op.f("ix_pedidos_incompletos_product_id"), table_name="pedidos_incompletos"
    )
    op.drop_index(
        op.f("ix_pedidos_incompletos_customer_order_id"),
        table_name="pedidos_incompletos",
    )
    op.drop_table("pedidos_incompletos")
    op.drop_index(op.f("ix_no_conformes_status"), table_name="no_conformes")
    op.drop_index(
        op.f("ix_no_conformes_purchase_invoice_id"), table_name="no_conformes"
    )
    op.drop_index(op.f("ix_no_conformes_product_id"), table_name="no_conformes")
    op.drop_index(op.f("ix_no_conformes_inventory_item_id"), table_name="no_conformes")
    op.drop_index(op.f("ix_no_conformes_folio"), table_name="no_conformes")
    op.drop_index(
        op.f("ix_no_conformes_external_product_id"), table_name="no_conformes"
    )
    op.drop_index(op.f("ix_no_conformes_detected_on"), table_name="no_conformes")
    op.drop_index(op.f("ix_no_conformes_customer_order_id"), table_name="no_conformes")
    op.drop_table("no_conformes")
    op.drop_index(op.f("ix_ventas_year_month"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_status"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_sold_on"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_quote_id"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_quadrimester"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_name"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_external_customer_id"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_customer_id"), table_name="ventas")
    op.drop_table("ventas")
    op.drop_index(
        op.f("ix_pedidos_proveedor_supplier_id"), table_name="pedidos_proveedor"
    )
    op.drop_index(
        op.f("ix_pedidos_proveedor_purchase_invoice_id"), table_name="pedidos_proveedor"
    )
    op.drop_index(
        op.f("ix_pedidos_proveedor_pickup_status"), table_name="pedidos_proveedor"
    )
    op.drop_index(
        op.f("ix_pedidos_proveedor_order_status"), table_name="pedidos_proveedor"
    )
    op.drop_index(
        op.f("ix_pedidos_proveedor_order_folio"), table_name="pedidos_proveedor"
    )
    op.drop_index(
        op.f("ix_pedidos_proveedor_generated_on"), table_name="pedidos_proveedor"
    )
    op.drop_index(
        op.f("ix_pedidos_proveedor_external_supplier_id"),
        table_name="pedidos_proveedor",
    )
    op.drop_table("pedidos_proveedor")
    op.drop_index(op.f("ix_pedidos_clientes_quote_id"), table_name="pedidos_clientes")
    op.drop_index(
        op.f("ix_pedidos_clientes_payment_status"), table_name="pedidos_clientes"
    )
    op.drop_index(op.f("ix_pedidos_clientes_ordered_on"), table_name="pedidos_clientes")
    op.drop_index(
        op.f("ix_pedidos_clientes_order_status"), table_name="pedidos_clientes"
    )
    op.drop_index(op.f("ix_pedidos_clientes_name"), table_name="pedidos_clientes")
    op.drop_index(
        op.f("ix_pedidos_clientes_external_customer_id"), table_name="pedidos_clientes"
    )
    op.drop_index(
        op.f("ix_pedidos_clientes_customer_id"), table_name="pedidos_clientes"
    )
    op.drop_index(
        op.f("ix_pedidos_clientes_customer_code"), table_name="pedidos_clientes"
    )
    op.drop_table("pedidos_clientes")
    op.drop_index(
        op.f("ix_entradas_mercancia_supplier_id"), table_name="entradas_mercancia"
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_received_on"), table_name="entradas_mercancia"
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_purchase_invoice_id"),
        table_name="entradas_mercancia",
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_product_id"), table_name="entradas_mercancia"
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_internal_code"), table_name="entradas_mercancia"
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_external_supplier_id"),
        table_name="entradas_mercancia",
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_external_product_id"),
        table_name="entradas_mercancia",
    )
    op.drop_index(
        op.f("ix_entradas_mercancia_entry_number"), table_name="entradas_mercancia"
    )
    op.drop_table("entradas_mercancia")
    op.drop_index(
        op.f("ix_cotizaciones_canceladas_quote_number"),
        table_name="cotizaciones_canceladas",
    )
    op.drop_index(
        op.f("ix_cotizaciones_canceladas_quote_id"),
        table_name="cotizaciones_canceladas",
    )
    op.drop_index(
        op.f("ix_cotizaciones_canceladas_external_customer_id"),
        table_name="cotizaciones_canceladas",
    )
    op.drop_index(
        op.f("ix_cotizaciones_canceladas_cancelled_on"),
        table_name="cotizaciones_canceladas",
    )
    op.drop_table("cotizaciones_canceladas")
    op.drop_index(op.f("ix_cotizacion_items_status"), table_name="cotizacion_items")
    op.drop_index(op.f("ix_cotizacion_items_sku"), table_name="cotizacion_items")
    op.drop_index(op.f("ix_cotizacion_items_quote_id"), table_name="cotizacion_items")
    op.drop_index(op.f("ix_cotizacion_items_product_id"), table_name="cotizacion_items")
    op.drop_index(
        op.f("ix_cotizacion_items_external_product_id"), table_name="cotizacion_items"
    )
    op.drop_index(
        op.f("ix_cotizacion_items_external_customer_id"), table_name="cotizacion_items"
    )
    op.drop_table("cotizacion_items")
    op.drop_index(
        "ix_csv_rows_file_row_number", table_name="csv_rows", schema="staging"
    )
    op.drop_table("csv_rows", schema="staging")
    op.drop_index(
        "ix_csv_row_errors_file_row_number",
        table_name="csv_row_errors",
        schema="staging",
    )
    op.drop_table("csv_row_errors", schema="staging")
    op.drop_index(
        op.f("ix_solicitudes_material_supplier_id"), table_name="solicitudes_material"
    )
    op.drop_index(
        op.f("ix_solicitudes_material_status"), table_name="solicitudes_material"
    )
    op.drop_index(
        op.f("ix_solicitudes_material_requested_on"), table_name="solicitudes_material"
    )
    op.drop_index(
        op.f("ix_solicitudes_material_product_sku"), table_name="solicitudes_material"
    )
    op.drop_index(
        op.f("ix_solicitudes_material_product_id"), table_name="solicitudes_material"
    )
    op.drop_index(
        op.f("ix_solicitudes_material_external_supplier_id"),
        table_name="solicitudes_material",
    )
    op.drop_index(
        op.f("ix_solicitudes_material_external_product_id"),
        table_name="solicitudes_material",
    )
    op.drop_table("solicitudes_material")
    op.drop_index(
        op.f("ix_movimientos_inventario_product_id"),
        table_name="movimientos_inventario",
    )
    op.drop_index(
        op.f("ix_movimientos_inventario_movement_type"),
        table_name="movimientos_inventario",
    )
    op.drop_index(
        op.f("ix_movimientos_inventario_moved_on"), table_name="movimientos_inventario"
    )
    op.drop_index(
        op.f("ix_movimientos_inventario_external_product_id"),
        table_name="movimientos_inventario",
    )
    op.drop_table("movimientos_inventario")
    op.drop_index(op.f("ix_inventario_product_id"), table_name="inventario")
    op.drop_index(op.f("ix_inventario_internal_code"), table_name="inventario")
    op.drop_index(op.f("ix_inventario_external_product_id"), table_name="inventario")
    op.drop_table("inventario")
    op.drop_index(
        op.f("ix_gastos_operativos_supplier_id"), table_name="gastos_operativos"
    )
    op.drop_index(op.f("ix_gastos_operativos_status"), table_name="gastos_operativos")
    op.drop_index(op.f("ix_gastos_operativos_spent_on"), table_name="gastos_operativos")
    op.drop_index(
        op.f("ix_gastos_operativos_payment_method"), table_name="gastos_operativos"
    )
    op.drop_index(
        op.f("ix_gastos_operativos_is_deductible"), table_name="gastos_operativos"
    )
    op.drop_index(
        op.f("ix_gastos_operativos_invoice_folio"), table_name="gastos_operativos"
    )
    op.drop_index(op.f("ix_gastos_operativos_category"), table_name="gastos_operativos")
    op.drop_table("gastos_operativos")
    op.drop_index(
        op.f("ix_facturas_compras_supplier_id"), table_name="facturas_compras"
    )
    op.drop_index(
        op.f("ix_facturas_compras_quote_number"), table_name="facturas_compras"
    )
    op.drop_index(
        op.f("ix_facturas_compras_payment_status"), table_name="facturas_compras"
    )
    op.drop_index(
        op.f("ix_facturas_compras_order_status"), table_name="facturas_compras"
    )
    op.drop_index(
        op.f("ix_facturas_compras_invoice_status"), table_name="facturas_compras"
    )
    op.drop_index(op.f("ix_facturas_compras_invoice_on"), table_name="facturas_compras")
    op.drop_index(
        op.f("ix_facturas_compras_invoice_number"), table_name="facturas_compras"
    )
    op.drop_index(
        op.f("ix_facturas_compras_external_supplier_id"), table_name="facturas_compras"
    )
    op.drop_table("facturas_compras")
    op.drop_index(op.f("ix_cotizaciones_status"), table_name="cotizaciones")
    op.drop_index(op.f("ix_cotizaciones_order_status"), table_name="cotizaciones")
    op.drop_index(op.f("ix_cotizaciones_name"), table_name="cotizaciones")
    op.drop_index(
        op.f("ix_cotizaciones_external_customer_id"), table_name="cotizaciones"
    )
    op.drop_index(op.f("ix_cotizaciones_customer_id"), table_name="cotizaciones")
    op.drop_index(op.f("ix_cotizaciones_customer_code"), table_name="cotizaciones")
    op.drop_index(op.f("ix_cotizaciones_created_on"), table_name="cotizaciones")
    op.drop_table("cotizaciones")
    op.drop_index("ix_csv_files_uploaded_at", table_name="csv_files", schema="staging")
    op.drop_index("ix_csv_files_dataset", table_name="csv_files", schema="staging")
    op.drop_table("csv_files", schema="staging")
    op.drop_index(op.f("ix_proveedores_name"), table_name="proveedores")
    op.drop_index(op.f("ix_proveedores_external_id"), table_name="proveedores")
    op.drop_table("proveedores")
    op.drop_index(op.f("ix_productos_sku"), table_name="productos")
    op.drop_index(op.f("ix_productos_name"), table_name="productos")
    op.drop_index(op.f("ix_productos_internal_code"), table_name="productos")
    op.drop_index(op.f("ix_productos_category"), table_name="productos")
    op.drop_table("productos")
    op.drop_index(op.f("ix_csv_import_runs_started_at"), table_name="csv_import_runs")
    op.drop_index(op.f("ix_csv_import_runs_dataset"), table_name="csv_import_runs")
    op.drop_table("csv_import_runs")
    op.drop_index(
        op.f("ix_crecimiento_inventario_registered_on"),
        table_name="crecimiento_inventario",
    )
    op.drop_index(
        op.f("ix_crecimiento_inventario_name"), table_name="crecimiento_inventario"
    )
    op.drop_index(
        op.f("ix_crecimiento_inventario_growth_type"),
        table_name="crecimiento_inventario",
    )
    op.drop_table("crecimiento_inventario")
    op.drop_index(op.f("ix_clientes_name"), table_name="clientes")
    op.drop_index(op.f("ix_clientes_external_id"), table_name="clientes")
    op.drop_table("clientes")
    op.execute("DROP SCHEMA IF EXISTS staging")
    # ### end Alembic commands ###
